title: Shit Karin Says
domain: shitkarinsays.com
baseurl: ""
github_username:  steve-gale
url: steve-gale.github.io
show_downloads: false

# Build settings
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-feed
  - jekyll-remote-theme
